# Generated by Django 5.2.7 on 2025-10-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="problem_url",
            field=models.URLField(
                blank=True, help_text="Full URL to the problem", null=True
            ),
        ),
        migrations.AddField(
            model_name="problem",
            name="tags",
            field=models.JSONField(
                blank=True, default=list, help_text="List of tags for the problem"
            ),
        ),
    ]
