# Generated by Django 5.2.7 on 2025-10-07 12:31

from django.db import migrations


def create_admin_plan(apps, schema_editor):
    """Create admin subscription plan"""
    SubscriptionPlan = apps.get_model('api', 'SubscriptionPlan')

    # Create or update admin plan
    admin_plan, created = SubscriptionPlan.objects.get_or_create(
        name='Admin',
        defaults={
            'description': 'Full access plan for administrators',
            'max_hints_per_day': -1,  # Unlimited
            'max_executions_per_day': -1,  # Unlimited
            'max_problems': -1,  # Unlimited
            'can_view_all_problems': True,
            'can_register_problems': True,
            'is_active': True,
        }
    )

    # Assign admin plan to all staff/superusers
    User = apps.get_model('api', 'User')
    User.objects.filter(is_staff=True).update(subscription_plan=admin_plan)
    User.objects.filter(is_superuser=True).update(subscription_plan=admin_plan)


def reverse_admin_plan(apps, schema_editor):
    """Remove admin plan"""
    SubscriptionPlan = apps.get_model('api', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(name='Admin').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_admin_plan, reverse_admin_plan),
    ]
