# Generated by Django 5.2.7 on 2025-10-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_problem_problem_url_problem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='constraints',
            field=models.TextField(blank=True, help_text='Input constraints for the problem', null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='language',
            field=models.CharField(blank=True, help_text='Programming language of solution', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_code',
            field=models.TextField(blank=True, help_text='Solution code for the problem', null=True),
        ),
    ]
