# Generated by Django 5.2.7 on 2025-10-07 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_create_admin_plan'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobProgressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('step', models.CharField(help_text='Step name (e.g., "Fetching problem", "Extracting constraints")', max_length=100)),
                ('message', models.TextField(help_text='Detailed progress message')),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'job_progress_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'created_at'], name='jph_job_created_idx')],
            },
        ),
    ]
