# Generated by Django 5.2.7 on 2025-10-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_problem_constraints_problem_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("problem_id", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("problem_url", models.URLField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("solution_code", models.TextField(blank=True, null=True)),
                ("language", models.CharField(max_length=50)),
                ("constraints", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("generator_code", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "script_generation_jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="script_gene_created_57c1a8_idx"
                    ),
                    models.Index(
                        fields=["status"], name="script_gene_status_1cff22_idx"
                    ),
                    models.Index(
                        fields=["celery_task_id"], name="script_gene_celery__b34aa7_idx"
                    ),
                ],
            },
        ),
    ]
