# Generated by Django 5.2.7 on 2025-10-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_scriptgenerationjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="is_completed",
            field=models.BooleanField(
                default=False, help_text="Whether the problem is completed/registered"
            ),
        ),
    ]
