# Generated by Django 5.2.7 on 2025-10-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_problem_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_plan_id_dynamodb",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
