# Generated by Django 5.2.7 on 2025-10-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_searchhistory_test_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible metadata field for storing additional information (e.g., execution_count, difficulty, etc.)'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extensible metadata field for storing additional information (e.g., execution time, memory usage, etc.)'),
        ),
    ]
