# Generated by Django 5.2.7 on 2025-10-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_problem_metadata_searchhistory_metadata"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcase",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="searchhistory",
            name="search_hist_created_e154e6_idx",
        ),
        migrations.RemoveIndex(
            model_name="searchhistory",
            name="search_hist_user_id_24152d_idx",
        ),
        migrations.RemoveIndex(
            model_name="searchhistory",
            name="search_hist_user_id_e4ac15_idx",
        ),
        migrations.RemoveIndex(
            model_name="testcase",
            name="test_cases_problem_eb1472_idx",
        ),
        migrations.RenameIndex(
            model_name="problem",
            new_name="problem_platform_id_idx",
            old_name="problems_platfor_abd684_idx",
        ),
        migrations.AlterField(
            model_name="problem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="is_completed",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the problem is completed/registered",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="language",
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="platform",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="problem",
            name="problem_id",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="problem",
            name="title",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="is_code_public",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="language",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="platform",
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="user_identifier",
            field=models.CharField(db_index=True, default="anonymous", max_length=100),
        ),
        migrations.AlterField(
            model_name="testcase",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["platform", "-created_at"], name="problem_platform_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["is_completed", "-created_at"],
                name="problem_completed_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["language", "-created_at"], name="problem_language_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="sh_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["is_code_public", "-created_at"], name="sh_public_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["user_identifier", "-created_at"],
                name="sh_userident_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["problem", "-created_at"], name="sh_problem_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["platform", "-created_at"], name="sh_platform_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["language", "-created_at"], name="sh_language_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["problem", "created_at"], name="test_cases_problem_c02b9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "-created_at"], name="user_active_created_idx"
            ),
        ),
    ]
