# Generated by Django 5.2.7 on 2025-10-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_optimize_testcase_searchhistory"),
        ("api", "0008_optimize_user_problem_indexes"),
    ]

    operations = []
