apiVersion: v2
name: algoitny-backend
description: AlgoItny Backend Service - Django REST API with Celery
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - django
  - celery
  - rest-api
  - algoitny
maintainers:
  - name: AlgoItny Team
home: https://testcase.run
sources:
  - https://github.com/yourusername/algoitny
