apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "algoitny-backend.fullname" . }}-config
  labels:
    {{- include "algoitny-backend.labels" . | nindent 4 }}
data:
  # Non-sensitive configuration
  DEBUG: {{ .Values.config.DEBUG | quote }}
  ALLOWED_HOSTS: {{ .Values.config.ALLOWED_HOSTS | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.config.CORS_ALLOWED_ORIGINS | quote }}
  CELERY_TASK_ALWAYS_EAGER: {{ .Values.config.CELERY_TASK_ALWAYS_EAGER | quote }}
  CELERY_RESULT_BACKEND: {{ .Values.config.CELERY_RESULT_BACKEND | quote }}
  JUDGE0_ENDPOINT: {{ .Values.config.JUDGE0_ENDPOINT | quote }}
