{{- if .Values.celeryWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "algoitny-backend.fullname" . }}-celery-worker
  labels:
    {{- include "algoitny-backend.celeryWorker.labels" . | nindent 4 }}
spec:
  {{- if not .Values.celeryWorker.keda.enabled }}
  replicas: {{ .Values.celeryWorker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "algoitny-backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: celery-worker
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "algoitny-backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: celery-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "algoitny-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: celery-worker
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - celery
          - -A
          - config
          - worker
          - --loglevel=info
          - --concurrency=${CELERY_CONCURRENCY}
          - --max-tasks-per-child=${CELERY_MAX_TASKS_PER_CHILD}
        envFrom:
        - configMapRef:
            name: {{ include "algoitny-backend.fullname" . }}-config
        - secretRef:
            name: {{ .Values.externalSecrets.secretName }}
        env:
        - name: CELERY_CONCURRENCY
          value: {{ .Values.celeryWorker.env.CELERY_CONCURRENCY | quote }}
        - name: CELERY_MAX_TASKS_PER_CHILD
          value: {{ .Values.celeryWorker.env.CELERY_MAX_TASKS_PER_CHILD | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - celery -A config inspect ping -d celery@$(POD_NAME)
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
