{{- if .Values.gunicorn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "algoitny-backend.fullname" . }}-gunicorn
  labels:
    {{- include "algoitny-backend.gunicorn.labels" . | nindent 4 }}
spec:
  {{- if not .Values.gunicorn.autoscaling.enabled }}
  replicas: {{ .Values.gunicorn.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "algoitny-backend.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gunicorn
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "algoitny-backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: gunicorn
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "algoitny-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: migration
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            echo "Running database migrations..."
            python manage.py migrate --noinput
            echo "Migrations completed successfully"
        envFrom:
        - configMapRef:
            name: {{ include "algoitny-backend.fullname" . }}-config
        - secretRef:
            name: {{ .Values.externalSecrets.secretName }}
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: {{ .Values.gunicorn.env.DJANGO_SETTINGS_MODULE }}
      containers:
      - name: gunicorn
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /bin/sh
          - -c
          - |
            gunicorn config.wsgi:application \
              --bind 0.0.0.0:8000 \
              --workers ${WORKERS} \
              --worker-class ${WORKER_CLASS} \
              --timeout ${TIMEOUT} \
              --access-logfile - \
              --error-logfile - \
              --log-level info
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "algoitny-backend.fullname" . }}-config
        - secretRef:
            name: {{ .Values.externalSecrets.secretName }}
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: {{ .Values.gunicorn.env.DJANGO_SETTINGS_MODULE }}
        - name: WORKERS
          value: {{ .Values.gunicorn.env.WORKERS | quote }}
        - name: WORKER_CLASS
          value: {{ .Values.gunicorn.env.WORKER_CLASS }}
        - name: TIMEOUT
          value: {{ .Values.gunicorn.env.TIMEOUT | quote }}
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          {{- toYaml .Values.gunicorn.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.gunicorn.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.gunicorn.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
