{{- if .Values.gunicorn.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "algoitny-backend.fullname" . }}-gunicorn
  labels:
    {{- include "algoitny-backend.gunicorn.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "algoitny-backend.fullname" . }}-gunicorn
  minReplicas: {{ .Values.gunicorn.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gunicorn.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.gunicorn.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.gunicorn.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.gunicorn.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.gunicorn.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max
{{- end }}
